# -*- mode: ruby -*-
# vi: set ft=ruby :

EXTERNAL_IP = ENV["EXTERNAL_IP"] || "172.28.128.16"

Vagrant.configure("2") do |config|
    config.vm.box = "fr123k/ubuntu21-minikube"
    config.vm.box_version = "1.0.0"

    config.vm.network "private_network", ip: EXTERNAL_IP

    config.vm.provision "shell", env: {"EXTERNAL_IP" => EXTERNAL_IP}, privileged: false, inline: <<-SHELL
        # Copy the deployment files
        mkdir /home/vagrant/ping
        cp /vagrant/*.yml /home/vagrant/ping
        cp /vagrant/Makefile /home/vagrant/ping
        minikube delete
        minikube start --apiserver-ips=${EXTERNAL_IP},10.0.2.15,10.96.0.1,127.0.0.1,10.0.0.1 --vm-driver none --kubernetes-version v1.21.0 --bootstrapper kubeadm
        minikube addons enable ingress
        sudo chown -R $USER $HOME/.kube $HOME/.minikube
        sleep 10
        cp /home/vagrant/.minikube/profiles/minikube/client.crt /vagrant/client.crt
        cp /home/vagrant/.minikube/profiles/minikube/client.key /vagrant/client.key
        cp /home/vagrant/.minikube/ca.crt /vagrant/ca.crt
    SHELL
end
